#spring.application.name=memberapp
#
#jwt.secret=jwttokenkeyforsecuritypurpose!@#$%^&*()124567890
#
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/membermanagementapp
#spring.datasource.username=postgres
#spring.datasource.password=01012020
#spring.jpa.hibernate.ddl-auto=none
#spring.flyway.enabled=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#flyway.ignoreUnsupportedDatabase=true
#spring.flyway.validate-on-migrate=false